const ORDER_STATUS = {
  PENDING: "PENDING",
  PROCESSING: "PROCESSING",
  COMPLETE: "COMPLETE",
};

const ORDER_TYPE = {
  NORMAL: "Normal",
  VIP: "VIP",
};

const BOT_STATUS = {
  ACTIVE: "ACTIVE",
  IDLE: "IDLE",
};

module.exports = { ORDER_STATUS, ORDER_TYPE, BOT_STATUS };
